pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Abhiabhi1019/CI-CD-for-a-Node.js-or-Python-app.git'
            }
        }

        stage('Setup Virtual Environment') {
            steps {
                dir('my-python-app') {
                    sh 'python3 -m venv venv'
                    sh 'source venv/bin/activate && pip install --upgrade pip'
                    sh 'source venv/bin/activate && pip install -r requirements.txt'
                }
            }
        }

        stage('Test / Run App') {
            steps {
                dir('my-python-app') {
                    sh 'source venv/bin/activate && python app.py'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('my-python-app') {
                    sh 'docker build -t my-python-app:latest .'
                }
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                docker rm -f my-python-app || true
                docker run -d -p 5000:5000 --name my-python-app my-python-app:latest
                '''
            }
        }
    }
}
