pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo "Cloning repository..."
                git branch: 'main', url: 'https://github.com/Abhiabhi1019/CI-CD-for-a-Node.js-or-Python-app.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('my-python-app') {
                    echo "Installing Python dependencies..."
                    sh 'pip install -r requirements.txt'
                }
            }
        }

        stage('Test') {
            steps {
                dir('my-python-app') {
                    echo "Running Python tests (if available)..."
                    sh 'pytest || echo "No tests found"'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('my-python-app') {
                    echo "Building Docker image for Python app..."
                    sh 'docker build -t my-python-app:latest .'
                }
            }
        }

        stage('Deploy Container') {
            steps {
                echo "Deploying Python container..."
                sh '''
                docker rm -f my-python-app || true
                docker run -d -p 5000:5000 --name my-python-app my-python-app:latest
                '''
            }
        }
    }
}
