pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo "Fetching code from GitHub..."
                git 'https://github.com/Abhiabhi1019/CI-CD-for-a-Node.js-or-Python-app.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                echo "Installing dependencies..."
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Test') {
            steps {
                echo "Running tests (if any)..."
                sh 'pytest || echo "No tests found"'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building Docker image..."
                sh 'docker build -t my-python-app:latest .'
            }
        }

        stage('Deploy Container') {
            steps {
                echo "Deploying container..."
                sh '''
                docker rm -f my-python-app || true
                docker run -d -p 5000:5000 --name my-python-app my-python-app:latest
                '''
            }
        }
    }
}
